spring:
  mvc:
    throw-exception-if-no-handler-found: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    generate-ddl: true
  h2:
    console:
      enabled: true

logging.level.io.github.kji6252.springvue.remote: DEBUG
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        readTimeout: 3000
        loggerLevel: FULL
      kakao:
        defaultRequestHeaders:
          Authorization: KakaoAK dc3e103ddc232c97b085faf8ba106db3
      naver:
        defaultRequestHeaders:
          X-Naver-Client-Id: ifxzPO_LDSLsCvXXMCyr
          X-Naver-Client-Secret: PQyCYfJCIi
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus
application:
  caches:
    queryBlogsFirstPage: maximumSize=1000, expireAfterWrite=60s, recordStats
    top10HotKeywords: maximumSize=1, expireAfterWrite=10s, recordStats
