spring:
  mvc:
    throw-exception-if-no-handler-found: false

logging.level.io.github.kji6252.springvue.remote.KakaoClient: DEBUG
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        readTimeout: 3000
        loggerLevel: FULL
      kakao:
        defaultRequestHeaders:
          Authorization:
      naver:
        defaultRequestHeaders:
          X-Naver-Client-Id:
          X-Naver-Client-Secret: