spring:
  mvc:
    throw-exception-if-no-handler-found: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    generate-ddl: true
  h2:
    console:
      enabled: true

logging.level.io.github.kji6252.springvue.remote: DEBUG
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        loggerLevel: FULL
      kakao:
        defaultRequestHeaders:
          Authorization:
      naver:
        defaultRequestHeaders:
          X-Naver-Client-Id:
          X-Naver-Client-Secret:
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        registerHealthIndicator: true
  timelimiter:
    configs:
      default:
        timeout-duration: 3s

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
application:
  caches:
    queryBlogsFirstPage: maximumSize=1000, expireAfterWrite=60s, recordStats
    top10HotKeywords: maximumSize=1, expireAfterWrite=10s, recordStats
